/**
 * Images Defines
 * @author Passion UI <passionui.com>
 */

export const Images = {
  logo: require("@assets/images/logo.png"),
  slide: require("@assets/images/image.png"),
  avata1: require("@assets/images/image.png"),
  avata2: require("@assets/images/image.png"),
  avata3: require("@assets/images/image.png"),
  avata4: require("@assets/images/image.png"),
  car1: require("@assets/images/image.png"),
  car2: require("@assets/images/image.png"),
  car3: require("@assets/images/image.png"),
  car4: require("@assets/images/image.png"),
  car5: require("@assets/images/image.png"),
  hotel1: require("@assets/images/image.png"),
  hotel2: require("@assets/images/image.png"),
  hotel3: require("@assets/images/image.png"),
  hotel4: require("@assets/images/image.png"),
  hotel5: require("@assets/images/image.png"),
  hotel6: require("@assets/images/image.png"),
  hotel7:require("@assets/images/image.png"),
  hotel8: require("@assets/images/image.png"),
  interio1: require("@assets/images/image.png"),
  interio2: require("@assets/images/image.png"),
  interio3: require("@assets/images/image.png"),
  interio4: require("@assets/images/image.png"),
  interio5: require("@assets/images/image.png"),
  interio6: require("@assets/images/image.png"),
  profile1: require("@assets/images/image.png"),
  profile2: require("@assets/images/image.png"),
  profile3: require("@assets/images/image.png"),
  profile4: require("@assets/images/image.png"),
  profile5: require("@assets/images/image.png"),
  profile6: require("@assets/images/image.png"),
  profile7: require("@assets/images/image.png"),
  profile8: require("@assets/images/image.png"),
  trip1: require("@assets/images/image.png"),
  trip2: require("@assets/images/image.png"),
  trip3: require("@assets/images/image.png"),
  trip4: require("@assets/images/image.png"),
  trip5: require("@assets/images/image.png"),
  trip6: require("@assets/images/image.png"),
  trip7: require("@assets/images/image.png"),
  trip8: require("@assets/images/image.png"),
  trip9: require("@assets/images/image.png"),
  room1: require("@assets/images/image.png"),
  room2: require("@assets/images/image.png"),
  room3: require("@assets/images/image.png"),
  room4: require("@assets/images/image.png"),
  room5: require("@assets/images/image.png"),
  room6: require("@assets/images/image.png"),
  room7: require("@assets/images/image.png"),
  room8: require("@assets/images/image.png"),
  room9: require("@assets/images/image.png"),
  room10: require("@assets/images/image.png"),
  room11: require("@assets/images/image.png"),
  background1: require("@assets/images/image.png"),
  background2: require("@assets/images/image.png"),
  background3: require("@assets/images/image.png"),
  background4: require("@assets/images/image.png"),
  banner1: require("@assets/images/image.png"),
  banner2: require("@assets/images/image.png"),
  airline1: require("@assets/images/image.png"),
  airline2: require("@assets/images/image.png"),
  airline3: require("@assets/images/image.png"),
  airline4: require("@assets/images/image.png"),
  cruise1: require("@assets/images/image.png"),
  cruise2: require("@assets/images/image.png"),
  cruise3: require("@assets/images/image.png"),
  cruise4: require("@assets/images/image.png"),
  brand1: require("@assets/images/image.png"),
  brand2: require("@assets/images/image.png"),
  brand3: require("@assets/images/image.png"),
  brand4: require("@assets/images/image.png"),
  event1: require("@assets/images/choose_language.png"),
  event2: require("@assets/images/image.png"),
  event3: require("@assets/images/image.png"),
  event4: require("@assets/images/image.png"),
  event5: require("@assets/images/image.png"),
  event6: require("@assets/images/image.png"),
  event7: require("@assets/images/image.png"),
  image: require("@assets/images/image.png")
};
