
require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '10.0'

target 'FelixPro' do
  config = use_native_modules!
  use_react_native!(:path => config["reactNativePath"])
  use_flipper!
  pod 'YouTubeSdk', :path => '../node_modules/react-native-youtube-sdk'

  pod 'react-native-config', :path => '../node_modules/react-native-config'

  pod 'react-native-netinfo', :path => '../node_modules/@react-native-community/netinfo'


  pod 'react-native-fetch-blob', :path => '../node_modules/react-native-fetch-blob'

  pod 'rn-fetch-blob', :path => '../node_modules/rn-fetch-blob'

  post_install do |installer|
    flipper_post_install(installer)
  end
  rn_maps_path = '../node_modules/react-native-maps'
  pod 'react-native-google-maps', :path => rn_maps_path
  pod 'GoogleMaps'
  pod 'Google-Maps-iOS-Utils'
end

